### ISSUE TITLE
Why should I have to install emacs to schedule shifts

### ISSUE THREAD

**Issue by DavidoRotho** [Staffjoy/v2#12]
### What environment did you encounter the issue in?

development

### Which browser are you using?

Chromium

### What did you do?

Tried to build

### What did you expect to see?

Built software

### What did you see instead?

`etags: command not found`

More of a complaint with the state of computing

**Comment by philipithomas** [comment]
Hi @DavidoRotho - this project isn't maintained anymore. It looks like you are referencing some architecture decisions. Other developers can't really use this constructively, so I'm closing the issue. If you think the code can be improved, we'd welcome a pull request :-)
