### ISSUE TITLE
Error building/running docker for V2

### ISSUE THREAD

**Issue by rmalla1** [Staffjoy/v2#3]
Hi there,

I am following instructions to build V2 on my local machine, and I see that compilation is successful.
However it fails during docker launch. This is a learning exercise for me to build software using GO.
Please find attached build logs.
Any help is appreciated.
Thanks.

> vagrant@staffjoy-v2:~/golang/src/v2.staffjoy.com$ make dev-build
make clean 
make[1]: Entering directory `/home/vagrant/golang/src/v2.staffjoy.com'
rm -rf vendor/
make[1]: Leaving directory `/home/vagrant/golang/src/v2.staffjoy.com'
bash ci/build.sh
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally cloud.google.com/go debdc0ca0113dd546ebebeb2000c9d938059f41d!
[INFO]	--> Found desired version locally github.com/certifi/gocertifi a61bf5eafa3aee233ec8043e9da052447e5463dd!
[INFO]	--> Found desired version locally github.com/dgrijalva/jwt-go d2709f9f1f31ebcda9651b03077758c1f3a0018c!
[INFO]	--> Found desired version locally github.com/dpapathanasiou/go-recaptcha 962f1d77fed91285eb86c988e3ae8e7948e554c8!
[INFO]	--> Found desired version locally github.com/elazarl/go-bindata-assetfs 9a6736ed45b44bf3835afeebb3034b57ed329f3e!
[INFO]	--> Found desired version locally github.com/fatih/structs dc3312cb1a4513a366c4c9e622ad55c32df12ed3!
[INFO]	--> Found desired version locally github.com/getsentry/raven-go 379f8d0a68ca237cf8893a1cdfd4f574125e2c51!
[INFO]	--> Found desired version locally github.com/go-gorp/gorp c87af80f3cc5036b55b83d77171e156791085e2e!
[INFO]	--> Found desired version locally github.com/go-sql-driver/mysql 0b58b37b664c21f3010e836f1b931e1d0b0b0685!
[INFO]	--> Found desired version locally github.com/gogo/protobuf a9cd0c35b97daf74d0ebf3514c5254814b2703b4!
[INFO]	--> Found desired version locally github.com/golang/appengine 926995697fa8241be2dc73eb318666e24f44ed51!
[INFO]	--> Found desired version locally github.com/golang/glog 23def4e6c14b4da8ac2ed8007337bc5eb5007998!
[INFO]	--> Found desired version locally github.com/golang/oauth2 3c3a985cb79f52a3190fbc056984415ca6763d01!
[INFO]	--> Found desired version locally github.com/golang/protobuf df1d3ca07d2d07bba352d5b73c4313b4e2a6203e!
[INFO]	--> Found desired version locally github.com/google/go-querystring 9235644dd9e52eeae6fa48efd539fdc351a0af53!
[INFO]	--> Found desired version locally github.com/google/google-api-go-client adba394bac5800ff2e620d040e9401528f5b7615!
[INFO]	--> Found desired version locally github.com/gorilla/context 08b5f424b9271eedf6f9f0ce86cb9396ed337a42!
[INFO]	--> Found desired version locally github.com/gorilla/csrf 50eb875b7d37289a5819742f0d60fa5c890fced9!
[INFO]	--> Found desired version locally github.com/gorilla/mux 0eeaf8392f5b04950925b8a69fe70f110fa7cbfc!
[INFO]	--> Found desired version locally github.com/gorilla/securecookie 667fe4e3466a040b780561fe9b51a83a3753eefc!
[INFO]	--> Found desired version locally github.com/gorilla/sessions ca9ada44574153444b00d3fd9c8559e4cc95f896!
[INFO]	--> Found desired version locally github.com/grpc-ecosystem/grpc-gateway a8f25bd1ab549f8b87afd48aa9181221e9d439bb!
[INFO]	--> Found desired version locally github.com/grpc/grpc-go 708a7f9f3283aa2d4f6132d287d78683babe55c8!
[INFO]	--> Found desired version locally github.com/intercom/intercom-go 2f809a5bfee1c01cbef2dd76453ef0f9123e289e!
[INFO]	--> Found desired version locally github.com/jteeuwen/go-bindata bbd0c6e271208dce66d8fda4bc536453cd27fc4a!
[INFO]	--> Found desired version locally github.com/keighl/mandrill 6a59523fcf7d27e9230141f0e2563ba976a92b8f!
[INFO]	--> Found desired version locally github.com/pkg/errors 645ef00459ed84a119197bfb8d8205042c6df63d!
[INFO]	--> Found desired version locally github.com/russross/blackfriday 5f33e7b7878355cd2b7e6b8eefc48a5472c69f70!
[INFO]	--> Found desired version locally github.com/shurcooL/sanitized_anchor_name 1dba4b3954bc059efc3991ec364f9f9a35f597d2!
[INFO]	--> Found desired version locally github.com/Sirupsen/logrus 4b6ea7319e214d98c938f12692336f7ca9348d6b!
[INFO]	--> Found desired version locally github.com/stretchr/testify f390dcf405f7b83c997eac1b06768bb9f44dec18!
[INFO]	--> Found desired version locally github.com/ttacon/builder 7f152c3cf4714fd6318739f8f3dbcd14c2a18b39!
[INFO]	--> Found desired version locally github.com/ttacon/libphonenumber 5cb77679a4c77d45f2496c9ed8e60b5eec03bb47!
[INFO]	--> Found desired version locally github.com/urfave/negroni fde5e16d32adc7ad637e9cd9ad21d4ebc6192535!
[INFO]	--> Found desired version locally golang.org/x/crypto 7682e7e3945130cf3cde089834664f68afdd1523!
[INFO]	--> Found desired version locally golang.org/x/net ffe101cce3477a6c6d8f0754d103bb0a84ec1266!
[INFO]	--> Found desired version locally golang.org/x/oauth2 3c3a985cb79f52a3190fbc056984415ca6763d01!
[INFO]	--> Found desired version locally golang.org/x/sys 8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9!
[INFO]	--> Found desired version locally golang.org/x/time 711ca1cb87636abec28122ef3bc6a77269d433f3!
[INFO]	--> Found desired version locally google.golang.org/api adba394bac5800ff2e620d040e9401528f5b7615!
[INFO]	--> Found desired version locally google.golang.org/appengine 926995697fa8241be2dc73eb318666e24f44ed51!
[INFO]	--> Found desired version locally google.golang.org/grpc 708a7f9f3283aa2d4f6132d287d78683babe55c8!
[INFO]	--> Found desired version locally gopkg.in/intercom/intercom-go.v2 2f809a5bfee1c01cbef2dd76453ef0f9123e289e!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew 2df174808ee097f90d259e432cc04442cf60be21!
[INFO]	--> Found desired version locally github.com/pmezard/go-difflib d8ed2627bdf02c080bf22230dbb337003b7aba2d!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/go-sql-driver/mysql to 0b58b37b664c21f3010e836f1b931e1d0b0b0685.
[INFO]	--> Setting version for github.com/dpapathanasiou/go-recaptcha to 962f1d77fed91285eb86c988e3ae8e7948e554c8.
[INFO]	--> Setting version for github.com/go-gorp/gorp to c87af80f3cc5036b55b83d77171e156791085e2e.
[INFO]	--> Setting version for github.com/gorilla/mux to 0eeaf8392f5b04950925b8a69fe70f110fa7cbfc.
[INFO]	--> Setting version for github.com/getsentry/raven-go to 379f8d0a68ca237cf8893a1cdfd4f574125e2c51.
[INFO]	--> Setting version for github.com/golang/glog to 23def4e6c14b4da8ac2ed8007337bc5eb5007998.
[INFO]	--> Setting version for github.com/golang/appengine to 926995697fa8241be2dc73eb318666e24f44ed51.
[INFO]	--> Setting version for github.com/gogo/protobuf to a9cd0c35b97daf74d0ebf3514c5254814b2703b4.
[INFO]	--> Setting version for github.com/certifi/gocertifi to a61bf5eafa3aee233ec8043e9da052447e5463dd.
[INFO]	--> Setting version for github.com/golang/oauth2 to 3c3a985cb79f52a3190fbc056984415ca6763d01.
[INFO]	--> Setting version for github.com/dgrijalva/jwt-go to d2709f9f1f31ebcda9651b03077758c1f3a0018c.
[INFO]	--> Setting version for github.com/fatih/structs to dc3312cb1a4513a366c4c9e622ad55c32df12ed3.
[INFO]	--> Setting version for github.com/elazarl/go-bindata-assetfs to 9a6736ed45b44bf3835afeebb3034b57ed329f3e.
[INFO]	--> Setting version for github.com/gorilla/context to 08b5f424b9271eedf6f9f0ce86cb9396ed337a42.
[INFO]	--> Setting version for github.com/gorilla/csrf to 50eb875b7d37289a5819742f0d60fa5c890fced9.
[INFO]	--> Setting version for github.com/gorilla/securecookie to 667fe4e3466a040b780561fe9b51a83a3753eefc.
[INFO]	--> Setting version for github.com/golang/protobuf to df1d3ca07d2d07bba352d5b73c4313b4e2a6203e.
[INFO]	--> Setting version for github.com/google/google-api-go-client to adba394bac5800ff2e620d040e9401528f5b7615.
[INFO]	--> Setting version for github.com/google/go-querystring to 9235644dd9e52eeae6fa48efd539fdc351a0af53.
[INFO]	--> Setting version for github.com/grpc/grpc-go to 708a7f9f3283aa2d4f6132d287d78683babe55c8.
[INFO]	--> Setting version for github.com/jteeuwen/go-bindata to bbd0c6e271208dce66d8fda4bc536453cd27fc4a.
[INFO]	--> Setting version for github.com/keighl/mandrill to 6a59523fcf7d27e9230141f0e2563ba976a92b8f.
[INFO]	--> Setting version for github.com/gorilla/sessions to ca9ada44574153444b00d3fd9c8559e4cc95f896.
[INFO]	--> Setting version for github.com/stretchr/testify to f390dcf405f7b83c997eac1b06768bb9f44dec18.
[INFO]	--> Setting version for github.com/intercom/intercom-go to 2f809a5bfee1c01cbef2dd76453ef0f9123e289e.
[INFO]	--> Setting version for github.com/grpc-ecosystem/grpc-gateway to a8f25bd1ab549f8b87afd48aa9181221e9d439bb.
[INFO]	--> Setting version for github.com/pkg/errors to 645ef00459ed84a119197bfb8d8205042c6df63d.
[INFO]	--> Setting version for github.com/ttacon/builder to 7f152c3cf4714fd6318739f8f3dbcd14c2a18b39.
[INFO]	--> Setting version for github.com/russross/blackfriday to 5f33e7b7878355cd2b7e6b8eefc48a5472c69f70.
[INFO]	--> Setting version for github.com/shurcooL/sanitized_anchor_name to 1dba4b3954bc059efc3991ec364f9f9a35f597d2.
[INFO]	--> Setting version for github.com/Sirupsen/logrus to 4b6ea7319e214d98c938f12692336f7ca9348d6b.
[INFO]	--> Setting version for github.com/urfave/negroni to fde5e16d32adc7ad637e9cd9ad21d4ebc6192535.
[INFO]	--> Setting version for github.com/ttacon/libphonenumber to 5cb77679a4c77d45f2496c9ed8e60b5eec03bb47.
[INFO]	--> Setting version for golang.org/x/crypto to 7682e7e3945130cf3cde089834664f68afdd1523.
[INFO]	--> Setting version for github.com/davecgh/go-spew to 2df174808ee097f90d259e432cc04442cf60be21.
[INFO]	--> Setting version for golang.org/x/net to ffe101cce3477a6c6d8f0754d103bb0a84ec1266.
[INFO]	--> Setting version for golang.org/x/oauth2 to 3c3a985cb79f52a3190fbc056984415ca6763d01.
[INFO]	--> Setting version for google.golang.org/api to adba394bac5800ff2e620d040e9401528f5b7615.
[INFO]	--> Setting version for github.com/pmezard/go-difflib to d8ed2627bdf02c080bf22230dbb337003b7aba2d.
[INFO]	--> Setting version for golang.org/x/sys to 8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9.
[INFO]	--> Setting version for google.golang.org/appengine to 926995697fa8241be2dc73eb318666e24f44ed51.
[INFO]	--> Setting version for gopkg.in/intercom/intercom-go.v2 to 2f809a5bfee1c01cbef2dd76453ef0f9123e289e.
[INFO]	--> Setting version for golang.org/x/time to 711ca1cb87636abec28122ef3bc6a77269d433f3.
[INFO]	--> Setting version for google.golang.org/grpc to 708a7f9f3283aa2d4f6132d287d78683babe55c8.
[INFO]	--> Setting version for cloud.google.com/go to debdc0ca0113dd546ebebeb2000c9d938059f41d.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/certifi/gocertifi
[INFO]	--> Exporting github.com/dgrijalva/jwt-go
[INFO]	--> Exporting github.com/elazarl/go-bindata-assetfs
[INFO]	--> Exporting github.com/dpapathanasiou/go-recaptcha
[INFO]	--> Exporting github.com/fatih/structs
[INFO]	--> Exporting github.com/google/google-api-go-client
[INFO]	--> Exporting github.com/go-sql-driver/mysql
[INFO]	--> Exporting github.com/gorilla/securecookie
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/golang/appengine
[INFO]	--> Exporting github.com/gorilla/csrf
[INFO]	--> Exporting github.com/golang/oauth2
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/google/go-querystring
[INFO]	--> Exporting github.com/go-gorp/gorp
[INFO]	--> Exporting github.com/gorilla/context
[INFO]	--> Exporting github.com/gorilla/mux
[INFO]	--> Exporting github.com/getsentry/raven-go
[INFO]	--> Exporting github.com/golang/glog
[INFO]	--> Exporting github.com/grpc/grpc-go
[INFO]	--> Exporting github.com/intercom/intercom-go
[INFO]	--> Exporting github.com/gorilla/sessions
[INFO]	--> Exporting github.com/grpc-ecosystem/grpc-gateway
[INFO]	--> Exporting github.com/shurcooL/sanitized_anchor_name
[INFO]	--> Exporting github.com/pkg/errors
[INFO]	--> Exporting github.com/stretchr/testify
[INFO]	--> Exporting github.com/jteeuwen/go-bindata
[INFO]	--> Exporting github.com/keighl/mandrill
[INFO]	--> Exporting github.com/Sirupsen/logrus
[INFO]	--> Exporting github.com/urfave/negroni
[INFO]	--> Exporting github.com/ttacon/builder
[INFO]	--> Exporting github.com/russross/blackfriday
[INFO]	--> Exporting github.com/ttacon/libphonenumber
[INFO]	--> Exporting github.com/pmezard/go-difflib
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	--> Exporting golang.org/x/oauth2
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting google.golang.org/api
[INFO]	--> Exporting gopkg.in/intercom/intercom-go.v2
[INFO]	--> Exporting google.golang.org/appengine
[INFO]	--> Exporting google.golang.org/grpc
[INFO]	--> Exporting golang.org/x/time
[INFO]	--> Exporting cloud.google.com/go
[INFO]	Replacing existing vendor dependencies
bash ci/dev-build.sh
++ date +%s
+ export VERSION=dev-1491587030
+ VERSION=dev-1491587030
+ export NAMESPACE=development
+ NAMESPACE=development
+ targets=("www" "faraday" "account/api" "account/server" "email/server" "myaccount" "whoami" "company/server" "company/api" "ical" "superpowers" "sms/server" "bot/server" "app")
+ declare -a targets
+ echo 'Running database migration'
Running database migration
+ migrate '-url=mysql://root:SHIBBOLETH@tcp(10.0.0.100:3306)/account' -path=/home/vagrant/golang/src/v2.staffjoy.com//account/migrations/ up

0.0062 seconds
+ migrate '-url=mysql://root:SHIBBOLETH@tcp(10.0.0.100:3306)/company' -path=/home/vagrant/golang/src/v2.staffjoy.com//company/migrations/ up

0.0042 seconds
+ for target in '"${targets[@]}"'
++ echo www
++ sed 's/\///g'
+ service=www
+ export service
+ bazel run //www:docker
INFO: Found 1 target...
Target //www:docker up-to-date:
  bazel-bin/www/docker-layer.tar
INFO: Elapsed time: 0.431s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/www/docker
Skipping ed58ca89a41518132e9c36c4e1851c670c8bc5764b63c5b5444cd31606dbe1b1, already loaded.
Skipping 4f1262fa8ea8bbbec4ae8a63c61953dea599cfee97a55ad216cc56d0cca560ed, already loaded.
Skipping 041c32df74204140dc63efde1441a4883a9c6206056b8122c5dc07e3f0a0b89d, already loaded.
Tagging 041c32df74204140dc63efde1441a4883a9c6206056b8122c5dc07e3f0a0b89d as bazel/www:docker
Error parsing reference: "041c32df74204140dc63efde1441a4883a9c6206056b8122c5dc07e3f0a0b89d" is not a valid repository/tag: invalid repository name (041c32df74204140dc63efde1441a4883a9c6206056b8122c5dc07e3f0a0b89d), cannot specify 64-byte hexadecimal strings
ERROR: Non-zero return code '1' from command: Process exited with status 1.
make: *** [dev-build] Error 6

>

**Comment by esurdam** [comment]
@rmalla1  Looks like Bazel isn't telling docker to tag it with "sha256:"

See this commit for fix: https://github.com/bazelbuild/bazel/commit/80ea129f7dfee37536110b2949c5a33f369fee10

**Comment by esurdam** [comment]
For a quick fix locate the following in `ci/dev-build.sh`

```
# Run the build and upload to GKE
bazel run //$target:docker
```

and change it to:

```
# Run the build and upload to GKE
# bazel run //$target:docker
bazel build //$target:docker
cat bazel-bin/$(echo $target)/docker | sed -e 's/tag ${name}/tag sha256:${name}/' > .docker.v2
sudo mv .docker.v2 bazel-bin/$(echo $target)/docker
chmod +x bazel-bin/$(echo $target)/docker
bazel-bin/$(echo $target)/docker
```

This will add the sha256 tag appropriately then load all the docker layers like `bazel run` would have

**Comment by rmalla1** [comment]
Thanks Evan. It works now.
