### ISSUE TITLE
Protobuf compiling fails

### ISSUE THREAD

**Issue by leandermelms** [Staffjoy/v2#5]
Hi, I successfully installed Staffjoy V2. I find the architecture used very interesting and I'm currently experiencing with it!

However, recompiling with `make protobuf` fails. I'm using Mac OS Sierra, Go 1.8, Vagrant 1.8.5.

I've tried to import `google.golang.org/grpc/status` into the Bazel build without any luck. Is this related to a version change in grpc-ecosystem/grpc-gateway?

Any help is greatly appreciated!

### What environment did you encounter the issue in?
account api

env: development

### What did you do?

Installed protoc-gen-gogo
```bash
go get github.com/gogo/protobuf/proto
go get github.com/gogo/protobuf/jsonpb
go get github.com/gogo/protobuf/protoc-gen-gogo
go get github.com/gogo/protobuf/gogoproto
go get github.com/gogo/protobuf/protoc-gen-gofast
```
And then recompiled with `make protobuf`

I also installed GNU sed

### What did you expect to see?
Protobuf recompilation without errors

### What did you see instead?
modd] ____Building...
[modd] ____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
[modd] ERROR: /home/vagrant/golang/src/v2.medjoy.com/account/api/BUILD:6:1: error executing shell command: 'set -e
[modd] export GOROOT="external/local_goroot"
[modd] rm -rf bazel-out/local-fastbuild/bin/account/api/accountapi.a.gopath/
[modd] mkdir bazel-out/local-fastbuild/bin/account/api/accountapi.a.gopath/
[modd] mkdir -p baze...' failed: Process exited with status 1 [sandboxed].
[modd] account/api/account.pb.gw.go:23: can't find import: "google.golang.org/grpc/status"
[modd] Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
[modd] Target //account/api:docker failed to build

### Are there any logs indicating an issue?
No.

**Comment by philipithomas** [comment]
Hmm, ok. Looks like a dependency issue. Specifically - it looks like github.com/gogo/protobuf/proto has been updated in a way that is not compatible with the [version of protobuf that is packaged in the app](https://github.com/Staffjoy/v2/blob/master/glide.lock#L44)

Could you try this?

```sh
go get github.com/golang/protobuf/...
cd $GOPATH/src/github.com/golang/protobuf/
# Switch to version that is packaged in app
git checkout df1d3ca07d2d07bba352d5b73c4313b4e2a6203e
# Re-install
go install github.com/golang/protobuf/proto
cd $GOPATH/src/v2.staffjoy.com/
make protobuf
``` 

If that doesn't work, I can spend more time looking at the issue tonight.

**Comment by leandermelms** [comment]
Thank you for the fast reply! You were right, it compiles now successfully!

The grpc-go package has changed accordingly at commit [b5071124392bfd416c713e6595ac149b387f7186](https://github.com/grpc/grpc-go/commit/b5071124392bfd416c713e6595ac149b387f7186):

> When an error implemented by the status package is returned from a service
> handler, the server will transmit a rich status message in the
> "grpc-status-details-bin" trailing metadata field if any detailed data is
> attached to the error.  Client-side, we will decode them if present in the
> server's response and return them to the user code performing the RPC.
> 
> This is backward compatible with the existing errors supported by the grpc
> package.  However, the grpc.Errorf, grpc.Code and grpc.ErrorDesc functions for
> managing errors are now deprecated; status.Errorf and status.Status type
> asserions should be used instead.

I also tried to update the build but as far as I can tell now, it is not a drop-in replacement. I'm new to protobuf, gRPC and bazel. If it helps I'll try to update gogo-protobuf to the latest version. 

Thank you for your help!

**Comment by philipithomas** [comment]
@leandermelms Great! Glad that solved it. Can you confirm that I can close this issue?

**Comment by leandermelms** [comment]
Yes, I tested it again on a different environment. It works!
This is one of the most inspiring projects in the Go community. Thank you for your help and sharing this!
