### ISSUE TITLE
Access apidocs

### ISSUE THREAD

**Issue by rmalla1** [Staffjoy/v2#8]
Hi there,
How would we access the apidocs on local machine?.
I tried apidocs.staffjoy-v2.local/ , it does'nt work.
I also tried looking for /swagger.json url, cant seem to find it.
Thanks,
Ratnakar

**Comment by philipithomas** [comment]
You access the API docs at:

account.staffjoy-v2.local/ui/

company.staffjoy-v2.local/ui

The Swagger docs are at:

account.staffjoy-v2.local/swagger.json

company.staffjoy-v2.local/swagger.json
